export const TIMER_RESET = 'TIMER_RESET'
export const TIMER_RESUME = 'TIMER_RESUME'
export const TIMER_PAUSE = 'TIMER_PAUSE'
export const TIMER_TOGGLE_ACTIVE = 'TIMER_TOGGLE_ACTIVE'
export const TIMER_TICK = 'TIMER_TICK'
export const TIMER_SETUP_INTERVAL = 'TIMER_SETUP_INTERVAL'

// Timer Settings
export const SET_INTERVAL_LENGTH = 'SET_INTERVAL_LENGTH'
export const SET_INTERVALS_PER_SESSION = 'SET_INTERVALS_PER_SESSION'

// Settings
export const OPEN_SETTING_MODAL = 'OPEN_SETTING_MODAL'
export const CLOSE_SETTING_MODAL = 'CLOSE_SETTING_MODAL'
export const UPDATE_USER_SETTING = 'UPDATE_USER_SETTING'
